##################################################################################
#         Calls workflow from code repo
##################################################################################
env:
  FIREBASE_SERVICE_ACCOUNT: ${{secrets.FIREBASE_SERVICE_ACCOUNT}} 
  FIREBASE_CONFIG_RELEASE: ${{secrets.FIREBASE_CONFIG_RELEASE}} 

name: Firebase - release

on:
  workflow_dispatch:

jobs:
  web_preview:
    uses: IDEMSInternational/open-app-builder/.github/workflows/reusable-deploy-web-preview.yml@master
    with: 
      firebase-host: ${{vars.FIREBASE_HOSTING_TARGET_RELEASE}} 
    secrets: 
      FIREBASE_PROJECT_ID: ${{vars.FIREBASE_PROJECT_ID}} 
      FIREBASE_HOSTING_CHANNEL: ${{vars.FIREBASE_HOSTING_CHANNEL}} 
      FIREBASE_HOSTING_TARGET: ${{vars.FIREBASE_HOSTING_TARGET}}  
      FIREBASE_SERVICE_ACCOUNT: ${{secrets.FIREBASE_SERVICE_ACCOUNT}} 
